[connections.snowflake]
account = "OFXNUGJ-DDB07199"  
user = "ankush123"
password = "Ankushmahore@2527"  # Use 'password', not 'private_key_file'
role = "sysadmin"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
